# Generated by Django 3.1.7 on 2021-07-09 03:59

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('password', fernet_fields.fields.EncryptedTextField(max_length=150)),
            ],
        ),
    ]
