# Generated by Django 3.1.7 on 2021-07-09 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_attend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='username',
        ),
    ]
