# Generated by Django 3.1.7 on 2021-07-09 04:02

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_attend', '0002_remove_person_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='username',
            field=fernet_fields.fields.EncryptedTextField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=fernet_fields.fields.EncryptedTextField(default=None, max_length=150),
        ),
    ]
