# Generated by Django 3.1.7 on 2021-07-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_attend', '0003_auto_20210709_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='collage',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='faculty',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='person',
            name='roll_no',
            field=models.SmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='person',
            name='section',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
