# Generated by Django 3.1.7 on 2021-07-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_attend', '0004_auto_20210709_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='roll_no',
            field=models.SmallIntegerField(default=0),
        ),
    ]
