# Generated by Django 3.1.7 on 2021-07-09 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_attend', '0006_remove_person_roll_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
