# Generated by Django 3.1.7 on 2021-07-09 04:18

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuse_attend', '0007_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('username', fernet_fields.fields.EncryptedTextField(default=None, max_length=150)),
                ('password', fernet_fields.fields.EncryptedTextField(default=None, max_length=150)),
                ('collage', models.CharField(default=None, max_length=100)),
                ('faculty', models.CharField(default=None, max_length=30)),
                ('section', models.CharField(default=None, max_length=15)),
                ('roll_no', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
