# Generated by Django 3.1.7 on 2021-07-09 04:21

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_attend', '0009_auto_20210709_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='password',
            field=fernet_fields.fields.EncryptedTextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=fernet_fields.fields.EncryptedTextField(max_length=150),
        ),
    ]
