# Generated by Django 3.1.7 on 2021-07-09 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_attend', '0012_person_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='token',
            new_name='auto_pseudoid',
        ),
    ]
