# Generated by Django 3.1.7 on 2021-07-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_attend', '0014_auto_20210709_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='person',
            name='level',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='login_url',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
