# Generated by Django 3.1.7 on 2021-05-27 19:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section_code', models.IntegerField(default=3030)),
                ('ioe_roll_no', models.CharField(max_length=12)),
                ('views', models.PositiveIntegerField(default=0)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], default='', max_length=1)),
                ('image_format', models.CharField(max_length=5)),
                ('ioe_roll_no_with_format', models.CharField(max_length=18)),
                ('collage', models.CharField(default=None, max_length=3, null=True)),
                ('faculty', models.CharField(default=None, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoundFemale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ranked_ids', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(default=None), default=None, null=True, size=None)),
                ('unranked_ids', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(default=None), default=None, null=True, size=None)),
                ('voted_people_of_level', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(default=None), default=None, null=True, size=None)),
                ('total_people_of_level', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(default=None), default=None, null=True, size=None)),
                ('random_pairs', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(default=None), default=None, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='RoundMale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ranked_ids', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(default=None), default=None, null=True, size=None)),
                ('unranked_ids', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(default=None), default=None, null=True, size=None)),
                ('total_people_of_level', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(default=None), default=None, null=True, size=None)),
                ('voted_people_of_level', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(default=None), default=None, null=True, size=None)),
                ('random_pairs', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(default=None), default=None, null=True, size=None)),
            ],
        ),
    ]
