# Generated by Django 3.1.7 on 2021-05-30 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotornot', '0002_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Feedbacks',
        ),
    ]
