# Generated by Django 3.1.7 on 2021-07-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotornot', '0003_auto_20210530_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='url',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
