# Generated by Django 3.2.6 on 2022-01-23 07:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IoeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default=None, max_length=500, null=True)),
                ('url', models.CharField(default=None, max_length=500, null=True)),
                ('date', models.CharField(default=None, max_length=35, null=True)),
                ('dob_ad', models.DateField(default=None, null=True)),
                ('sent', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=6), default=None, null=True, size=None)),
            ],
        ),
        migrations.AddIndex(
            model_name='ioenotification',
            index=models.Index(fields=['title'], name='api_ioenoti_title_755a50_idx'),
        ),
        migrations.AddIndex(
            model_name='ioenotification',
            index=models.Index(fields=['title'], name='title'),
        ),
    ]
