# Generated by Django 3.2.6 on 2022-01-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IoeNotification',
            new_name='IoeNoti',
        ),
        migrations.RemoveIndex(
            model_name='ioenoti',
            name='api_ioenoti_title_755a50_idx',
        ),
        migrations.AddIndex(
            model_name='ioenoti',
            index=models.Index(fields=['title'], name='api_ioenoti_title_829660_idx'),
        ),
    ]
