# Generated by Django 3.2.6 on 2022-01-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220123_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ioenoti',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ioenoti',
            name='url',
            field=models.CharField(db_index=True, default=None, max_length=500, null=True),
        ),
    ]
