# Generated by Django 3.2.6 on 2022-01-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220123_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ioenoti',
            name='url',
            field=models.CharField(db_index=True, default=None, max_length=500, null=True, unique=True),
        ),
    ]
