# Generated by Django 4.1.5 on 2023-07-02 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
