# Generated by Django 4.1.3 on 2023-01-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_share", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="code",
            name="stars",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
