# Generated by Django 3.2.6 on 2021-12-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toycomment',
            old_name='uuid',
            new_name='id',
        ),
    ]
