# Generated by Django 3.2.6 on 2021-12-28 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='hide_code',
            new_name='private_code',
        ),
    ]
