# Generated by Django 3.2.6 on 2021-12-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0002_codebranch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codebranch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
