# Generated by Django 3.2.6 on 2021-12-06 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0002_rename_uuid_toycomment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toycomment',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
