# Generated by Django 3.2.6 on 2022-01-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0002_rename_hide_code_branch_private_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, null=True)),
                ('image', models.ImageField(null=True, upload_to='category/')),
            ],
        ),
    ]
