# Generated by Django 3.2.6 on 2022-01-25 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0002_auto_20220125_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='parent_code',
        ),
        migrations.AddField(
            model_name='code',
            name='output_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='code_share.photo'),
        ),
    ]
