# Generated by Django 3.2.6 on 2021-12-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0003_alter_toycomment_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToyComment',
            new_name='Code',
        ),
    ]
