# Generated by Django 4.1.5 on 2023-07-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0003_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_path',
        ),
    ]
