# Generated by Django 3.2.6 on 2022-01-05 15:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0003_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='stars_ip',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
