# Generated by Django 3.2.6 on 2021-12-18 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0003_alter_codebranch_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodeBranch',
            new_name='Branch',
        ),
    ]
