# Generated by Django 3.2.6 on 2022-01-25 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0003_auto_20220125_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='parent_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='code_share.code'),
        ),
    ]
