# Generated by Django 3.2.6 on 2021-12-20 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0004_rename_codebranch_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='originalCode',
            new_name='Parent',
        ),
    ]
