# Generated by Django 3.2.6 on 2021-12-07 14:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0004_rename_toycomment_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='comment',
            new_name='code',
        ),
        migrations.AddField(
            model_name='code',
            name='hide_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='code',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='code',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='code',
            name='valid_email',
            field=models.BooleanField(default=True),
        ),
    ]
