# Generated by Django 3.2.6 on 2022-01-05 15:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0004_auto_20220105_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='stars_ip',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), default=None, null=True, size=None),
        ),
    ]
