# Generated by Django 3.2.6 on 2022-01-25 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0004_photo_parent_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='output_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='code_share.photo'),
        ),
    ]
