# Generated by Django 4.1.5 on 2023-07-08 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0004_remove_file_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
