# Generated by Django 4.1.5 on 2023-07-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0005_file_created_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
