# Generated by Django 4.0.2 on 2022-02-22 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0005_alter_code_output_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='Branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_branch', to='code_share.branch'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='Parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b_parent', to='code_share.code'),
        ),
    ]
