# Generated by Django 3.2.2 on 2021-12-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0005_auto_20211207_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='author',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='code',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
