# Generated by Django 3.2.6 on 2022-01-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0005_alter_code_stars_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='author_ip',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
