# Generated by Django 3.2.6 on 2021-12-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0005_rename_originalcode_branch_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='star',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='code',
            name='stars',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
