# Generated by Django 4.1.5 on 2023-07-08 14:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0006_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('unique_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(default='anonymous', max_length=80)),
                ('author_email', models.EmailField(default='', max_length=254)),
                ('is_private', models.BooleanField(default=False)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), default=None, null=True, size=None)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('author_ip', models.CharField(default='', max_length=25)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('stars_ip', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), default=None, null=True, size=None)),
                ('valid_email', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('type', models.CharField(choices=[('text', 'Text'), ('img', 'Image'), ('other', 'Other')], max_length=10)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='code_share.container')),
            ],
        ),
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='code_share.container')),
            ],
        ),
    ]
