# Generated by Django 4.0.2 on 2022-02-22 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0006_code_branch_alter_branch_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='Branch',
        ),
        migrations.AlterField(
            model_name='branch',
            name='Parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='code_share.code'),
        ),
    ]
