# Generated by Django 3.2.2 on 2021-12-10 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0006_auto_20211210_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
