# Generated by Django 4.1.5 on 2023-07-08 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0007_container_files_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='unique_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
