# Generated by Django 3.2.6 on 2021-12-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0007_useremail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEmail',
        ),
    ]
