# Generated by Django 4.0.2 on 2022-05-26 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0007_remove_code_branch_alter_branch_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='author_ip',
        ),
    ]
