# Generated by Django 3.2.6 on 2021-12-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0008_delete_useremail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='hide_code',
        ),
        migrations.AddField(
            model_name='code',
            name='private_code',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
