# Generated by Django 4.0.2 on 2022-05-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0008_remove_code_author_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='author_ip',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
