# Generated by Django 4.0.2 on 2022-05-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0009_code_author_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='author_ip',
            field=models.CharField(default='', max_length=25),
        ),
    ]
