# Generated by Django 4.1.5 on 2023-07-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0009_alter_container_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='codes',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
