# Generated by Django 4.1.5 on 2023-07-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0010_files_name_alter_codes_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='name',
            new_name='filename',
        ),
    ]
