# Generated by Django 3.2.6 on 2021-12-28 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0010_alter_code_private_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='private_code',
            new_name='hide_code',
        ),
    ]
