# Generated by Django 4.1.5 on 2023-07-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0011_rename_name_files_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='name',
            field=models.CharField(default='code', max_length=15),
        ),
    ]
