# Generated by Django 4.1.5 on 2023-07-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0012_codes_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codes',
            old_name='name',
            new_name='codename',
        ),
    ]
