# Generated by Django 4.1.5 on 2023-07-23 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0013_rename_name_codes_codename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codes',
            old_name='codename',
            new_name='filename',
        ),
    ]
