# Generated by Django 4.1.5 on 2023-07-23 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0014_rename_codename_codes_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='download_link',
            field=models.URLField(default=''),
        ),
    ]
