# Generated by Django 4.1.5 on 2023-07-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0015_files_download_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='google_drive_file_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
