# Generated by Django 4.1.5 on 2023-10-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0016_files_google_drive_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='filename',
            field=models.CharField(default='code', max_length=20),
        ),
    ]
