# Generated by Django 4.1.5 on 2023-10-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_share', '0017_alter_codes_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='filename',
            field=models.CharField(default='code', max_length=25),
        ),
    ]
