# Generated by Django 3.2.6 on 2021-12-19 17:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import nepali_datetime_field.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(default='', max_length=750)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ioe_roll_no', models.CharField(db_index=True, default=None, max_length=30, null=True, unique=True)),
                ('empty_profile', models.BooleanField(db_index=True, default=False)),
                ('nick_name', models.CharField(default='', max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(db_index=True, max_length=30)),
                ('last_name', models.CharField(db_index=True, max_length=30)),
                ('dob_bs', nepali_datetime_field.models.NepaliDateField(default='2058-12-28')),
                ('dob_ad', models.DateField(default=None, null=True)),
                ('dob', models.DateField(default=None, null=True)),
                ('profession', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), db_index=True, default=None, null=True, size=None)),
                ('personality', models.CharField(max_length=30)),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), default=None, null=True, size=None)),
                ('post_box', models.IntegerField(default=None, null=True)),
                ('permanent_address', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), default=None, null=True, size=None)),
                ('uses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), default=None, null=True, size=None)),
                ('social_engineering', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), default=None, null=True, size=None)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('l', 'female'), ('g', 'female'), ('o', 'other')], default='', max_length=1)),
                ('fathers_name', models.CharField(default=None, max_length=100, null=True)),
                ('mothers_name', models.CharField(default=None, max_length=100, null=True)),
                ('location', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=None, null=True, size=None)),
                ('phone_number', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=0, default=0, max_digits=10), db_index=True, default=None, null=True, size=None)),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), db_index=True, default=None, null=True, size=None)),
                ('adress', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300), default=None, null=True, size=None)),
                ('likes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), db_index=True, default=None, null=True, size=None)),
                ('dislikes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), db_index=True, default=None, null=True, size=None)),
                ('religion', models.CharField(db_index=True, max_length=25)),
                ('country', models.CharField(db_index=True, max_length=25)),
                ('hobbies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), default=None, null=True, size=None)),
                ('family_members', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), default=None, null=True, size=None)),
                ('education', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), default=None, null=True, size=None)),
                ('smoke', models.BooleanField(default=None, null=True)),
                ('drink', models.BooleanField(default=None, null=True)),
                ('rating', models.IntegerField(default=10)),
                ('symbols', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=None, null=True, size=None)),
                ('profile_pic', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), default=None, null=True, size=None)),
                ('last_edit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('ioe_roll_no', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('urls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), default=None, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='test_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_num', models.DecimalField(decimal_places=0, default=9999999999, max_digits=10)),
                ('name', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, default=None, max_length=300)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_url', models.CharField(blank=True, default=None, max_length=300)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name', 'first_name'], name='person_pers_last_na_9b7b87_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['first_name'], name='first_name_idx'),
        ),
        migrations.AddField(
            model_name='name',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
    ]
