# Generated by Django 4.1.3 on 2023-01-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0005_userdata_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
